### ISSUE TITLE
Impossible to change the route once it's calculated

### ISSUE THREAD

**Issue by jbelien** [oSoc17/rideaway-frontend#3]
Once a route si calculated, it's impossible to change the origin or the destination to calculate a new route.
Need to be fixed !

```
Error: There is already a source with this ID
```

**Comment by ArnaudWeyts** [comment]
Fixed in ac14184

**Comment by jbelien** [comment]
It's not fixed.

Once a route is calculated, I can change the origin and the origin marker is moved but the new route is **not** calculated and if I change the destination, same `Error: There is already a source with this ID` error.

**Comment by jbelien** [comment]
Sorry, I just saw all the changes are done in `develop` so I can't try it yet.
